### ISSUE TITLE
[feature request] Highlight variables in template literals

### ISSUE THREAD

**Issue by kuba-orlik** [emacs-typescript/typescript.el#133] opened 2020-03-25 12:57 UTC
Currently typescript-mode does not highlight values inside template literals:

![image](https://user-images.githubusercontent.com/2697916/77538710-0ec38380-6e98-11ea-99c6-7c9f3ec465c6.png)

`js2-mode` handles that well and I sometimes find myself switching between the two when working with template literals:

![image](https://user-images.githubusercontent.com/2697916/77538753-26027100-6e98-11ea-8aa4-fbfb30b65de8.png)

**Comment by lddubeau** [comment] 2020-03-25 13:17
Duplicate of #48 

PR welcome.

**Closed by lddubeau** 2020-03-25 13:17 UTC
