### ISSUE TITLE
indent-region formats code inside template strings

### ISSUE THREAD

**Issue by rogergl** [emacs-typescript/typescript.el#5] opened 2015-10-24 07:54 UTC
Maybe prog-indent-sexp should ignore the content of template strings ?

**Comment by lddubeau** [comment] 2019-03-08 17:43
This sounds like the same thing as I reported (much later) in #47. Since #47 has an illustration of the problem and discussion, I'm closing in favor of #47. If I misunderstood the issue reported here, please add a case that reproduces the problem and distinguishes it from #47.

**Closed by lddubeau** 2019-03-08 17:43 UTC
