### ISSUE TITLE
Support arrow functions

### ISSUE THREAD

**Issue by TatriX** [emacs-typescript/typescript.el#18] opened 2016-08-29 14:43 UTC
There is no support for syntax highlighting of the arrow function formal parameters, `beginning-of-defun` etc.

**Comment by lddubeau** [comment] 2019-03-08 17:21
I'm closing this due to the lack of an actual case illustrating the problem. I'll gladly reopen once a case other people can use to reproduce the problem is added to this issue. I use `typescript-mode` day in and day out and don't recall a specific problem with highlighting arrow functions. Maybe it's been fixed while fixing another problem... hard to tell without a case.

**Closed by lddubeau** 2019-03-08 17:21 UTC
